CREATE TABLE Game (
                      game_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      home_club_id INT NOT NULL REFERENCES club(club_id),
                      away_club_id INT NOT NULL REFERENCES club(club_id),
                      game_date DATE NOT NULL,
                      home_club_score INT NOT NULL CHECK (home_club_score >= 0),
                      away_club_score INT NOT NULL CHECK (away_club_score >= 0)
)