CREATE TABLE Club (
                      club_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      club_name VARCHAR(100) NOT NULL,
                      country_id INT NOT NULL REFERENCES country(country_id) ON DELETE RESTRICT
);